# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20160316_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='identificador',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
